version: '3'

services:
  integration:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionString=Server=db;Integrated Security=False;Database=master;User Id=sa;Password=TestTest123;
    entrypoint: bash /app/wait_for_it.sh db:1433 -t 0 -- dotnet test
    depends_on:
      - db
  db:
    image: microsoft/mssql-server-linux
    ports:
      - 1433:1433
    volumes:
      - /var/opt/mssql
      - ./Scripts:/usr/src/app 
    working_dir: /usr/src/app
    command: sh -c ' chmod +x ./entrypoint.sh; ./entrypoint.sh & /opt/mssql/bin/sqlservr;'
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=TestTest123